version: '2'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app/build
    networks:
      - my_network

  backend:
    depends_on:
      - db
    links:
      - db:db
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0'
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - my_network

  db:
    container_name: "db"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=kolkhoz
      - POSTGRES_PASSWORD=kolkhoz
      - POSTGRES_DB=kolkhoz
    networks:
      - my_network
    ports:
      - "5432:5432"

networks:
  my_network:
