FROM python:3.10-bullseye
WORKDIR /app

COPY ./requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./compile_files ./compile_files
COPY ./compile_files_ota ./compile_files_ota
COPY ./db ./db
COPY ./lib ./lib
COPY ./tests ./tests
COPY ./uploaded_files ./uploaded_files
COPY ./main.py ./main.py
COPY ./settings.py ./settings.py
COPY ./manifest.json ./manifest.json
COPY ./hashing.py ./hashing.py
COPY ./api ./api
COPY ./migrations ./migrations
COPY ./alembic.ini ./alembic.ini
COPY ./pytest.ini ./pytest.ini

EXPOSE 8000

#CMD ["bash", "-c", "alembic upgrade head && sed -i 's#sqlalchemy.url = postgresql://kolkhoz:kolkhoz@db:5432/kolkhoz#sqlalchemy.url = postgresql://testkolkhoz:testkolkhoz@test-db:5432/testkolkhoz#g' alembic.ini && pytest tests && sed -i 's#sqlalchemy.url = postgresql://testkolkhoz:testkolkhoz@test-db:5432/testkolkhoz#sqlalchemy.url = postgresql://kolkhoz:kolkhoz@db:5432/kolkhoz#g' alembic.ini && uvicorn main:app --reload --host 0.0.0.0"]