version: '2'
services:

  backend:
    depends_on:
      - db
      - test-db
    links:
      - db:db
      - test-db:test-db
    build:
      context: .
      dockerfile: Dockerfile-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - my_network

  db:
    container_name: "db"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=kolkhoz
      - POSTGRES_PASSWORD=kolkhoz
      - POSTGRES_DB=kolkhoz
    ports:
      - "5432:5432"
    networks:
      - my_network

  test-db:
    container_name: "test-db"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=testkolkhoz
      - POSTGRES_PASSWORD=testkolkhoz
      - POSTGRES_DB=testkolkhoz
    networks:
      - my_network
    ports:
      - "5433:5432"

networks:
  my_network:
