version: '2'
services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - my_network

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
