"""add user_id in userconfig

Revision ID: 281ae72c3d23
Revises: 
Create Date: 2023-06-10 11:12:15.653121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281ae72c3d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
