"""create db

Revision ID: 9fed58a95781
Revises: 
Create Date: 2023-06-17 19:38:15.122755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fed58a95781'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('name_config', sa.UUID(), nullable=False),
    sa.Column('hash_yaml', sa.String(), nullable=True),
    sa.Column('compile_test', sa.Boolean(), nullable=True),
    sa.Column('name_esphome', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('name_config')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name_config', sa.UUID(), nullable=True),
    sa.Column('name_esphome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['name_config'], ['config.name_config'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_config')
    op.drop_table('users')
    op.drop_table('config')
    # ### end Alembic commands ###
