"""add user_id in userconfig

Revision ID: cefd93dab163
Revises: 281ae72c3d23
Create Date: 2023-06-10 11:12:26.716286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefd93dab163'
down_revision = '281ae72c3d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_config', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user_config', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_config', type_='foreignkey')
    op.drop_column('user_config', 'user_id')
    # ### end Alembic commands ###
