name: Pull Request

on:
  pull_request:
    branches:
      - master
      - tests
  push:
    branches:
      - master
      - tests

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Replace Docker Compose command
        run: |
          sed -i "s|^\s*command:.*|    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && pytest tests'|" docker-compose.yaml
      - name: Run Docker Compose
        run: docker-compose up --build backend db
