name: Pull Request

on:
  pull_request:
    branches:
      - master
  push:
    branches: []

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Replace Docker Compose command
        run: |
          sed -i 's/uvicorn main:app --reload --host 0.0.0.0/pytest tests/' docker-compose.yaml
      - name: Show Updated Docker Compose File
        run: cat docker-compose.yaml
      - name: Run Docker Compose
        run: |
          docker-compose up --build --exit-code-from backend backend db
          CONTAINER_EXIT_CODE=$(docker-compose ps -q backend | xargs docker inspect -f '{{.State.ExitCode}}')
          if [ $CONTAINER_EXIT_CODE -eq 0 ]; then
            echo "Container 'backend' exited successfully."
            exit 0
          else
            echo "Container 'backend' exited with an error code: $CONTAINER_EXIT_CODE"
            exit 1
          fi
